#include<iostream>
#include "Increment.h"

using namespace std;

/*OSSERVARE LA STRUTTURA DEL COSTRUTTORE DI INCREMENT:
  - UN INIZIALIZZATORE PER UN DATO MEMBRO È "UNA FUNZIONE"
    COL NOME DEL DATO MEMBRO STESSO CHE PRENDE COME ARGOMENTO IL 
    VALORE COL QUALE SI INTENDE INIZIALIZZARE IL DATO MEMBRO.
  - È POSSIBILE PASSARE UNA "COMMA-SEPARATED LIST" DI INIZIALIZZATORI
    PONENDO " : " DOPO LE PARENTESI TONDE CHE CONTENGONO LA LISTA DEI 
    PARAMETRI
  - È TASSATIVO UTILIZZARE GLI INIZIALIZZATORI PER INIZIALIZZRE DATI MEMBRO
    const (NON È INFATTI POSSIBILE FARLO TRAMITE IL SEMPLICE ASSEGNAMENTO)   
  */

Increment::Increment(int c = 0, int i = 1) :
        count(c),
        increment(i)
{
    
}

void Increment::printCount() const {
  cout << "count = " << count << endl;
}
